### ISSUE TITLE
Player Selection & Replays empty on Windows 10 x64 v2.1.3

### ISSUE THREAD

**Issue by Dave247** [eivindveg/HotSUploader#148]
I'm not sure if there's something I'm not doing but I haven't been able to find any instructions anywhere.

I've installed the exe successfully on WIndows 10 x64, and the program runs but when I click the drop down box under the players tab it's empty,  Also there are no detected replays either.

However the app does seem to be able to detect when I am in a game and who the teams are.

**Comment by eivindveg** [comment]
Are you able to provide the verbatim output of the following cmd command?

```
reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v personal
```

If it displays any personal information and you feel you need to censor it, please make sure that the replaced values conform to the same pattern, ie:
- Digit is replaced with digit
- Lowercase character in standard character set(a-z) is replaced with another lowercase character in the same character set. Same applies for non-standard characters(æøå, Arabic, Russian, etc), and also uppercase for uppercase.

Note to other developers: In the case of a coding error, the offending code is located at https://github.com/eivindveg/HotSUploader/blob/develop/src/main/java/ninja/eivind/hotsreplayuploader/services/platform/WindowsService.java#L102-L137, specifically the fallback at line [131](https://github.com/eivindveg/HotSUploader/blob/develop/src/main/java/ninja/eivind/hotsreplayuploader/services/platform/WindowsService.java#L131)

**Comment by Dave247** [comment]
Here is the output, hopefully in the correct format. 

    HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
        personal    REG_SZ    C:\Users\david\OneDrive\Dave-i7\Documents

Just to mention I've set moved my documents folder into Onedrive so everything there can be backed up for safe keeping, though I'm not sure if this has any relevance.

**Comment by eivindveg** [comment]
Output is good, just what I need! I'm going to take a guess - my regular expression for identifying that string still isn't good enough. I'll update it as necessary to make sure it captures that folder properly. We'll have this fixed in either 2.1.4 or 2.2.0 over the holidays.

**Comment by Dave247** [comment]
Glad to now it helps! I'll keep an eye out for when there's an update and let you know if it's fixed in a future version.

**Comment by eivindveg** [comment]
Note to self: Having reviewed the regex it does not seem to capture some part of the "-i7" segment, either the '-' or the '7'. The regex should be updated to remove any restrictions but valid Windows paths to prevent similar issues in the future.

**Comment by eivindveg** [comment]
I am terribly sorry this is not fixed before. We're opening development for 2.1.4, and this issue will be included.

**Comment by Dave247** [comment]
That's alright I understand you've probabbly had many other things to do other then just work on this project. I look forward to it being fixed though so I can then use your program from then on!

**Comment by eivindveg** [comment]
Hi Dave. This issue will be fixed in the upcoming 2.1.4 release scheduled for today. Happy uploading!

**Comment by Dave247** [comment]
Woo! Thanks much for this, I can finally be able to upload brawl matches! That was one of the main things I wanted to use your uploader for, and how it is overall has more features and functionality then the regular client.

I'll close this ticket for now and if any other issues arise I'll be sure to open a new one for it. ^_^
