### ISSUE TITLE
Replace JSON file store with JDBC data store

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#47]
Currently, due to the minimum block size of my SSD, each replay property file takes up 256kb disk space. This is far more than necessary, and should be alleviated by replacing the structure with a light-weight file-based database, such as H2. For simplicity, an ORM should be added for the ReplayFile and UploadStatus models, but without the full weight of Hibernate or other heavy weights. ORMLite is an option, but that project largely seems abandoned.

This will also result in an actually upgradeable file store.

**Comment by zhedar** [comment]
I recommend having a look at [Berkeley DB](http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html). It offers an API called DPL, that you can you use to perform objectoriented queries. It is able to run in embedded mode and has no further dependencies.

Quote from an [Oracle article](http://www.oracle.com/technetwork/products/berkeleydb/performing.pdf):
> The DPL offers many of the same benefits of Java Persistence APIs that perform object-to-relational mapping within Enterprise Java Beans 3.0 (EJB3), but without the need to translate objects into SQL expressions persisted in relational tables. This is accomplished without losing any of the transactional (ACID), concurrent, or scalability qualities provided by RDBMS systems.

**Comment by eivindveg** [comment]
It is however, even more outdated than ORMLite, which offers very JPA-like functionality as well.

**Comment by zhedar** [comment]
The versions in the maven repos seem to be severly outdated. There is a [never version in the repo](http://mvnrepository.com/artifact/com.sleepycat/je), but it is still outdated. The [current version](http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html?ssSourceSiteId=ocomen) is from 08.2015 and seems to be still actively supported by Oracle.

**Comment by eivindveg** [comment]
Got a working prototype for ORMLite, as that's on Maven Central. However, this is a really volatile setup at the moment and is suitable only for testing since one has to kill their database quite often.

It's worth reviewing, but could change completely at a moment's notice.

**Comment by eivindveg** [comment]
DataStore now has migrations, doesn't take ages to start up, and is completely independent of the StormHandler. We're close to being completely rid of that one now.

**Comment by zhedar** [comment]
Is this ready to be merged into the dev branch, so we could test this for some runs with all recent changes? My current application hangs after resetting the Json files and I want to make sure this isn't a blocker bug with the upload logic.

**Comment by eivindveg** [comment]
The remaining issues, if any, can be fixed in dev, staging or a minor release. Merging.

**Comment by eivindveg** [comment]
That merge went as bad as it could have. Too many conflicts to keep it straight. Application is currently broken. Will debug and fix after dinner.

**Comment by zhedar** [comment]
Well it's a development branch after all, you won't hurt anybody with the merge. 
I can no longer reproduce the issue I previously had, atleast with the original branch. Running my uploads on develop again and I'm halfway through without any errors.

**Comment by eivindveg** [comment]
I assume the issues are in the WatchHandler. Everything goes bad and stops what it's doing when new files are detected. This is, however, a massive copy-paste. Maybe I have an excuse for playing a few games. ;D

**Comment by eivindveg** [comment]
Fixed. Everything seems stable again. Had a double handle that did some weird things. =)

**Comment by zhedar** [comment]
Cannot confirm, everything still crashing. I have pulled your latest changes now and will start with a fresh db again. I also tried to isolate the files, which are causing problems. I may sent them to you, if I won't get any further. Would that be ok?

**Comment by eivindveg** [comment]
Feel free to mail them over, and I'll see if there's something in the parser going bad. Otherwise, we should just escape that file and send it directly to upload.

**Comment by zhedar** [comment]
It doesn't look like, its the actual file, which is causing the trouble. If I remove the problematic files and rerun again, it also hangs on the last 9 files (which always happened to be cursed hallow). Also I see no notification on the tray, is that already active?

**Comment by eivindveg** [comment]
Last nine files? Probably the tray notifications. I personally found those annoying while playing just now, so we might just remove that part.

**Comment by zhedar** [comment]
Yeah, get rid of them. If we do that, we could also cancel #69, because that's the OS X version of them though. If we keep them, it would be better to put a notification out, when all files are uploaded, not under 10 I guess.

**Comment by eivindveg** [comment]
Keeping that issue open, but not integrating for 2.0. Dropping notifications.

**Comment by eivindveg** [comment]
Do we consider this issue closed now?

**Comment by zhedar** [comment]
DB integration works as JsonFileStore did before. It may need some tuning (we should probably turn off debug logging as well), but yeah, we should probably integrate #70 before closing.

**Comment by eivindveg** [comment]
Switched off debug logging.

**Comment by eivindveg** [comment]
Closed by 72e1a767677d7a2e08f84babc7d349b2b4e23719
